# Generated by Django 5.2.1 on 2025-07-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='updated_by',
        ),
    ]
