# Generated by Django 5.2.1 on 2025-06-20 00:48

import uuid
from django.db import migrations, models


def generate_uuid(apps, schema_editor):
    """Generate UUIDs for existing wishlist records"""
    Wishlist = apps.get_model('wishlist', 'Wishlist')
    
    for wishlist in Wishlist.objects.all():
        wishlist.new_id = uuid.uuid4()
        wishlist.save(update_fields=['new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_recreate_wishlist'),
    ]

    operations = [
        # Step 1: Add new UUID field
        migrations.AddField(
            model_name='wishlist',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Remove old primary key
        migrations.RemoveField(
            model_name='wishlist',
            name='id',
        ),
        
        # Step 4: Rename new_id to id and make it primary key
        migrations.RenameField(
            model_name='wishlist',
            old_name='new_id',
            new_name='id',
        ),
        
        # Step 5: Set as primary key
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ] 