# Generated by Django 5.2.1 on 2025-06-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_fix_wishlist_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'managed': True, 'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
    ]
