# Generated by Django 5.2.1 on 2025-06-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_fix_user_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'managed': True, 'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='wishlist_wishlist',
        ),
    ]
