# Generated by Django 5.2.1 on 2025-06-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlist_options_alter_wishlist_table'),
        ('wishlist', '0004_fix_wishlist_columns'),
    ]

    operations = [
    ]
