# Generated by Django 5.2.1 on 2025-06-25 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storestaff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storestaff',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storestaff',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_store_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storestaff',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='owner', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='storestaff',
            unique_together={('store', 'user')},
        ),
    ]
