# Generated by Django 5.2.1 on 2025-08-14 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0032_merchantsettlementaccount'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Store wallet for payment processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='bank.wallet'),
        ),
        migrations.AddField(
            model_name='store',
            name='xy_save_account',
            field=models.ForeignKey(blank=True, help_text='XySave account for store payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_stores', to='bank.xysaveaccount'),
        ),
    ]
