# Generated by Django 5.2.1 on 2025-06-27 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='store',
            name='store_store_status_cb0145_idx',
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='store_store_owner_i_0a6f7a_idx',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='store_store_status_565347_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner'], name='store_store_owner_i_d4e5f2_idx'),
        ),
    ]
