# Generated by Django 5.2.1 on 2025-08-14 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_wallet_store_xy_save_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated the store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
