# Generated by Django 5.2.1 on 2025-07-02 14:43

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_storestaff_store_store_store_i_abbfa2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storestaff',
            name='store_store_role_59dbdf_idx',
        ),
        migrations.RemoveField(
            model_name='store',
            name='auto_approve_products',
        ),
        migrations.RemoveField(
            model_name='store',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='storestaff',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storestaff',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='storestaff',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Whatsapp profile URL', max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddIndex(
            model_name='storestaff',
            index=models.Index(fields=['role'], name='store_store_role_29598c_idx'),
        ),
    ]
