# Generated by Django 5.2.1 on 2025-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_file_message_image_message_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
