# Generated by Django 5.2.1 on 2025-05-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_store_contact_email_store_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
