# Generated by Django 5.2.1 on 2025-06-20 00:48

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    """Generate UUIDs for all existing product model records"""
    Bundle = apps.get_model('product', 'Bundle')
    BundleItem = apps.get_model('product', 'BundleItem')
    Category = apps.get_model('product', 'Category')
    Coupon = apps.get_model('product', 'Coupon')
    CouponUsage = apps.get_model('product', 'CouponUsage')
    DynamicPricing = apps.get_model('product', 'DynamicPricing')
    FlashSale = apps.get_model('product', 'FlashSale')
    FlashSaleItem = apps.get_model('product', 'FlashSaleItem')
    Product = apps.get_model('product', 'Product')
    ProductReview = apps.get_model('product', 'ProductReview')
    ProductVariant = apps.get_model('product', 'ProductVariant')
    Subcategory = apps.get_model('product', 'Subcategory')
    Subscription = apps.get_model('product', 'Subscription')
    SubscriptionItem = apps.get_model('product', 'SubscriptionItem')
    
    # Generate UUIDs for all models
    for model_class in [Bundle, BundleItem, Category, Coupon, CouponUsage, 
                       DynamicPricing, FlashSale, FlashSaleItem, Product, 
                       ProductReview, ProductVariant, Subcategory, Subscription, SubscriptionItem]:
        for obj in model_class.objects.all():
            obj.new_id = uuid.uuid4()
            obj.save(update_fields=['new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        # Step 1: Add new UUID fields for all models
        migrations.AddField(
            model_name='bundle',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='dynamicpricing',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='flashsaleitem',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Remove old primary key fields
        migrations.RemoveField(model_name='bundle', name='id'),
        migrations.RemoveField(model_name='bundleitem', name='id'),
        migrations.RemoveField(model_name='category', name='id'),
        migrations.RemoveField(model_name='coupon', name='id'),
        migrations.RemoveField(model_name='couponusage', name='id'),
        migrations.RemoveField(model_name='dynamicpricing', name='id'),
        migrations.RemoveField(model_name='flashsale', name='id'),
        migrations.RemoveField(model_name='flashsaleitem', name='id'),
        migrations.RemoveField(model_name='product', name='id'),
        migrations.RemoveField(model_name='productreview', name='id'),
        migrations.RemoveField(model_name='productvariant', name='id'),
        migrations.RemoveField(model_name='subcategory', name='id'),
        migrations.RemoveField(model_name='subscription', name='id'),
        migrations.RemoveField(model_name='subscriptionitem', name='id'),
        
        # Step 4: Rename new_id to id for all models
        migrations.RenameField(model_name='bundle', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='bundleitem', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='category', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='coupon', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='couponusage', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='dynamicpricing', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='flashsale', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='flashsaleitem', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='product', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='productreview', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='productvariant', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='subcategory', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='subscription', old_name='new_id', new_name='id'),
        migrations.RenameField(model_name='subscriptionitem', old_name='new_id', new_name='id'),
        
        # Step 5: Set all id fields as primary keys
        migrations.AlterField(
            model_name='bundle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dynamicpricing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flashsaleitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ] 