# Generated by Django 5.2.1 on 2025-06-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productvariant_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchfilter',
            name='rating_min',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
