# Generated by Django 5.2.1 on 2025-07-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_add_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
    ]
