# Generated by Django 5.2.1 on 2025-07-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_add_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='individual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Specific price for this variant (used when pricing_mode is 'individual')", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='pricing_mode',
            field=models.CharField(choices=[('adjustment', 'Price Adjustment'), ('individual', 'Individual Price')], default='adjustment', help_text='Price adjustment: adds to product base price. Individual price: sets specific price for this variant.', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('style', 'Style'), ('material', 'Material'), ('other', 'Other')], default='other', help_text='Type of variant (color, size, style, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Amount to add/subtract from product base price (used when pricing_mode is 'adjustment')", max_digits=10),
        ),
    ]
