# Generated by Django 5.2.1 on 2025-06-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='extras_addr_is_acti_4ab8f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='extras_addr_is_veri_8c4948_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='address',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='address',
            name='verification_date',
        ),
    ]
