# Generated by Django 5.2.1 on 2025-06-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_remove_address_extras_addr_is_acti_4ab8f8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(help_text='Geographic latitude coordinate', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(help_text='Geographic longitude coordinate', verbose_name='Longitude'),
        ),
    ]
