# Generated by Django 5.2.1 on 2025-06-18 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='12345', help_text='Postal or ZIP code', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code (e.g., 12345 or 12345-6789)', regex='^\\d{5}(-\\d{4})?$')], verbose_name='Postal Code'),
        ),
    ]
