# Generated by Django 5.2.1 on 2025-06-21 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the notification.', max_length=255, verbose_name='Title')),
                ('message', models.TextField(help_text='The main content of the notification.', verbose_name='Message')),
                ('link', models.URLField(blank=True, help_text='An optional URL to direct the user to.', max_length=255, null=True, verbose_name='Link')),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('order_status_update', 'Order Status Update'), ('password_reset', 'Password Reset'), ('promotion', 'Promotion'), ('new_message', 'New Message'), ('system_alert', 'System Alert'), ('wishlist_update', 'Wishlist Update'), ('review_reminder', 'Review Reminder'), ('other', 'Other')], default='other', help_text='The category of the notification.', max_length=30, verbose_name='Notification Type')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='The importance level of the notification (e.g., info, warning).', max_length=10, verbose_name='Level')),
                ('isRead', models.BooleanField(default=False, help_text='Whether the user has read the notification.', verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the notification was created.', verbose_name='Created At')),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, help_text='The user or system sending the notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'isRead'], name='notificatio_recipie_4ddb72_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_a5f01d_idx')],
            },
        ),
    ]
