# Generated by Django 5.2.1 on 2025-07-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_status_update', 'Order Status Update'), ('order_cancelled', 'Order Cancelled'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('new_message', 'New Message'), ('system_alert', 'System Alert'), ('wishlist_update', 'Wishlist Update'), ('review_reminder', 'Review Reminder'), ('stock_alert', 'Stock Alert'), ('price_drop', 'Price Drop'), ('shipping_update', 'Shipping Update'), ('refund_processed', 'Refund Processed'), ('account_update', 'Account Update'), ('security_alert', 'Security Alert'), ('escalation', 'Escalation'), ('other', 'Other'), ('sms', 'Sms'), ('email', 'Email'), ('push', 'Push'), ('bank_transaction', 'Bank Transaction'), ('bank_transfer', 'Bank Transfer'), ('bill_payment', 'Bill Payment'), ('wallet_credit', 'Wallet Credited'), ('wallet_debit', 'Wallet Debited')], db_index=True, default='other', help_text='The category of the notification', max_length=30, verbose_name='Notification Type'),
        ),
    ]
