# Generated by Django 5.2.1 on 2025-06-27 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
        ('order', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_notifications', 'Can view all notifications'), ('manage_notifications', 'Can manage notifications')], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_a5f01d_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='userId',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', help_text='Current status of the notification', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user associated with this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, help_text='Text for the action button', max_length=64, verbose_name='Action Text'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL for the action button', max_length=500, null=True, verbose_name='Action URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the notification was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the notification was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Additional data for this notification (JSON format)', null=True, verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the notification', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the user has read the notification', verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this notification has been soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('low', 'Low'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', help_text='The importance level of the notification', max_length=10, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='An optional URL to direct the user to', max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='The main content of the notification', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_status_update', 'Order Status Update'), ('order_cancelled', 'Order Cancelled'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('new_message', 'New Message'), ('system_alert', 'System Alert'), ('wishlist_update', 'Wishlist Update'), ('review_reminder', 'Review Reminder'), ('stock_alert', 'Stock Alert'), ('price_drop', 'Price Drop'), ('shipping_update', 'Shipping Update'), ('refund_processed', 'Refund Processed'), ('account_update', 'Account Update'), ('security_alert', 'Security Alert'), ('other', 'Other')], db_index=True, default='other', help_text='The category of the notification', max_length=30, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='orderId',
            field=models.ForeignKey(blank=True, help_text='The order associated with this notification, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Priority of the notification (higher = more important)', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the notification was read', null=True, verbose_name='Read At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The user or system sending the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(blank=True, help_text='Source app or module that generated this notification', max_length=64, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_index=True, help_text='The title of the notification', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the notification was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_eb34ac_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'level'], name='notificatio_recipie_50282a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_18c9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'level'], name='notificatio_notific_67829e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_deleted', 'created_at'], name='notificatio_is_dele_c50c69_idx'),
        ),
    ]
