# Generated by Django 5.2.1 on 2025-08-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_status_update', 'Order Status Update'), ('order_cancelled', 'Order Cancelled'), ('order_delivered', 'Order Delivered'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('new_message', 'New Message'), ('system_alert', 'System Alert'), ('wishlist_update', 'Wishlist Update'), ('review_reminder', 'Review Reminder'), ('stock_alert', 'Stock Alert'), ('price_drop', 'Price Drop'), ('shipping_update', 'Shipping Update'), ('refund_processed', 'Refund Processed'), ('account_update', 'Account Update'), ('security_alert', 'Security Alert'), ('escalation', 'Escalation'), ('other', 'Other'), ('sms', 'Sms'), ('email', 'Email'), ('push', 'Push'), ('bank_transaction', 'Bank Transaction'), ('bank_transfer', 'Bank Transfer'), ('bill_payment', 'Bill Payment'), ('wallet_credit', 'Wallet Credited'), ('wallet_debit', 'Wallet Debited'), ('spend_and_save_activation', 'Spend and Save Activation'), ('spend_and_save_deactivation', 'Spend and Save Deactivation'), ('automatic_save', 'Automatic Save'), ('savings_milestone', 'Savings Milestone'), ('interest_credited', 'Interest Credited'), ('savings_withdrawal', 'Savings Withdrawal'), ('weekly_savings_summary', 'Weekly Savings Summary'), ('savings_goal_achieved', 'Savings Goal Achieved'), ('target_saving_created', 'Target Saving Created'), ('target_saving_updated', 'Target Saving Updated'), ('target_saving_completed', 'Target Saving Completed'), ('target_saving_deposit', 'Target Saving Deposit'), ('target_saving_milestone', 'Target Saving Milestone'), ('target_saving_overdue', 'Target Saving Overdue'), ('target_saving_reminder', 'Target Saving Reminder'), ('target_saving_withdrawal', 'Target Saving Withdrawal'), ('fixed_savings_created', 'Fixed Savings Created'), ('fixed_savings_activated', 'Fixed Savings Activated'), ('fixed_savings_matured', 'Fixed Savings Matured'), ('fixed_savings_paid_out', 'Fixed Savings Paid Out'), ('fixed_savings_interest_credited', 'Fixed Savings Interest Credited'), ('fixed_savings_auto_renewal', 'Fixed Savings Auto Renewal'), ('fixed_savings_maturity_reminder', 'Fixed Savings Maturity Reminder'), ('fixed_savings_early_withdrawal', 'Fixed Savings Early Withdrawal')], db_index=True, default='other', help_text='The category of the notification', max_length=35, verbose_name='Notification Type'),
        ),
    ]
