# Generated by Django 5.2.1 on 2025-07-20 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
                ('ussd', models.CharField(blank=True, help_text='USSD code for the bank', max_length=20, null=True)),
                ('logo', models.URLField(blank=True, help_text='URL to bank logo', null=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('teller', 'Teller'), ('customer_service', 'Customer Service Representative'), ('personal_banker', 'Personal Banker'), ('assistant_manager', 'Assistant Manager'), ('manager', 'Manager'), ('branch_manager', 'Branch Manager')], max_length=50, unique=True)),
                ('level', models.IntegerField(help_text='Hierarchical level (1=lowest, 6=highest)')),
                ('description', models.TextField()),
                ('max_transaction_approval', models.DecimalField(decimal_places=2, default=0, help_text='Maximum transaction amount this role can approve', max_digits=15)),
                ('can_approve_kyc', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_override_transactions', models.BooleanField(default=False)),
                ('can_handle_escalations', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TransferChargeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levy_active', models.BooleanField(default=True, help_text='Apply CBN levy to transfers?')),
                ('vat_active', models.BooleanField(default=True, help_text='Apply VAT to transfers?')),
                ('fee_active', models.BooleanField(default=True, help_text='Apply transfer fee to transfers?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transfer Charge Control',
                'verbose_name_plural': 'Transfer Charge Controls',
            },
        ),
        migrations.CreateModel(
            name='VATCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, default=0.075, help_text='VAT rate as a decimal (e.g., 0.075 for 7.5%)', max_digits=5)),
                ('active', models.BooleanField(default=True, help_text='Is this the current VAT rate?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VAT Charge',
                'verbose_name_plural': 'VAT Charges',
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, help_text='Recipient bank code', max_length=10, null=True)),
                ('account_number', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('levy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('account_or_meter', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CBNVATCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbn_vat_charge', to='bank.banktransfer')),
            ],
            options={
                'verbose_name': 'CBN VAT Charge',
                'verbose_name_plural': 'CBN VAT Charges',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(blank=True, help_text='Branch or location', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField()),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='bank.staffprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='bank.staffrole')),
            ],
            options={
                'ordering': ['role__level', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('transaction_processed', 'Transaction Processed'), ('kyc_approved', 'KYC Approved'), ('escalation_handled', 'Escalation Handled'), ('customer_served', 'Customer Served'), ('report_generated', 'Report Generated'), ('staff_managed', 'Staff Managed')], max_length=50)),
                ('description', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bank.staffprofile')),
            ],
            options={
                'verbose_name_plural': 'Staff Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_assigned', to='bank.staffprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_created', to='bank.staffprofile')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('channel', models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit'), ('bill', 'Bill Payment')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=10)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Wallet balance after this transaction', max_digits=12, null=True)),
                ('currency', models.CharField(default='NGN', help_text='Transaction currency', max_length=5)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Extra metadata for this transaction', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, help_text='Original transaction if this is a reversal/refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='bank.transaction')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for approval/rejection')),
                ('escalation_reason', models.TextField(blank=True, help_text='Reason for escalation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to='bank.staffprofile')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_received', to='bank.staffprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='bank.staffprofile')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='bank.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiry', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virtual Card',
                'verbose_name_plural': 'Virtual Cards',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10, unique=True)),
                ('alternative_account_number', models.CharField(max_length=10, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.wallet'),
        ),
    ]
