# Generated by Django 5.2.1 on 2025-07-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='Receiver wallet for transfers (null for non-transfer transactions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='bank.wallet'),
        ),
    ]
