# Generated by Django 5.2.1 on 2025-07-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transaction_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('intra', 'Intra-bank'), ('inter', 'Inter-bank')], default='inter', help_text='Type of transfer: intra-bank (internal) or inter-bank (external)', max_length=10),
        ),
    ]
