# Generated by Django 5.2.1 on 2025-07-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_banktransfer_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description of the transfer', max_length=255, null=True),
        ),
    ]
