# Generated by Django 5.2.1 on 2025-07-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_banktransfer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='nibss_reference',
            field=models.CharField(blank=True, help_text='NIBSS transaction reference', max_length=64, null=True),
        ),
    ]
