# Generated by Django 5.2.1 on 2025-07-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_banktransfer_nibss_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
