# Generated by Django 5.2.1 on 2025-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_banktransfer_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
