# Generated by Django 5.2.1 on 2025-07-25 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_billpayment_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the transfer was approved', null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved this transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for transfer failure if status is Failed', null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether this transfer requires staff approval'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Transfer status: Pending, Completed, or Failed', max_length=10),
        ),
    ]
