# Generated by Django 5.2.1 on 2025-07-30 19:44

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_bank_id_alter_banktransfer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0.0'), default_currency='NGN', max_digits=19),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0.0'), default_currency='NGN', max_digits=19),
        ),
        migrations.AlterField(
            model_name='cbnvatcharge',
            name='vat_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0.0'), default_currency='NGN', max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0.0'), default_currency='NGN', max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default=Decimal('0.0'), default_currency='NGN', help_text='Wallet balance after this transaction', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0.0'), default_currency='NGN', max_digits=19),
        ),
    ]
