# Generated by Django 5.2.1 on 2025-08-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_transferfailure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfailure',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Device fingerprint for fraud detection', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transferfailure',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent from request', null=True),
        ),
    ]
