# Generated by Django 5.2.1 on 2025-08-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_make_user_agent_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfailure',
            name='recipient_bank_code',
            field=models.CharField(blank=True, help_text='Bank code for external transfers', max_length=10, null=True),
        ),
    ]
