# Generated by Django 5.2.1 on 2025-08-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_alter_transferfailure_recipient_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Transfer status: Pending, Processing, Successful, Completed, or Failed', max_length=10),
        ),
    ]
