# Generated by Django 5.2.1 on 2025-08-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_add_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
