# Generated by Django 5.2.1 on 2025-08-07 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_spendandsaveaccount_spendandsavesettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSaving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Target Name')),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('education', 'Education'), ('business', 'Business'), ('japa', 'Japa (Relocation)'), ('vehicle', 'Vehicle'), ('wedding', 'Wedding'), ('emergency', 'Emergency Fund'), ('investment', 'Investment'), ('travel', 'Travel'), ('home_renovation', 'Home Renovation'), ('medical', 'Medical'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Target Amount')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, verbose_name='Frequency')),
                ('preferred_deposit_day', models.CharField(blank=True, help_text='Day of week for weekly/monthly deposits', max_length=20, null=True, verbose_name='Preferred Deposit Day')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Current Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Target Saving',
                'verbose_name_plural': 'Target Savings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetSavingDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Deposit Amount')),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('target_saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='bank.targetsaving')),
            ],
            options={
                'verbose_name': 'Target Saving Deposit',
                'verbose_name_plural': 'Target Saving Deposits',
                'ordering': ['-deposit_date'],
            },
        ),
        migrations.AddIndex(
            model_name='targetsaving',
            index=models.Index(fields=['user', 'is_active'], name='bank_target_user_id_36a97b_idx'),
        ),
        migrations.AddIndex(
            model_name='targetsaving',
            index=models.Index(fields=['user', 'category'], name='bank_target_user_id_6664a8_idx'),
        ),
        migrations.AddIndex(
            model_name='targetsaving',
            index=models.Index(fields=['end_date'], name='bank_target_end_dat_71d4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='targetsavingdeposit',
            index=models.Index(fields=['target_saving', 'deposit_date'], name='bank_target_target__58849a_idx'),
        ),
    ]
