# Generated by Django 5.2.1 on 2025-08-08 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_fixedsavingsaccount_fixedsavingssettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedsavingsaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_savings_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
