# Generated by Django 5.2.1 on 2025-08-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_alter_fixedsavingsaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendandsavesettings',
            name='funding_preference',
            field=models.CharField(choices=[('auto', 'Auto (prefer XySave, fallback Wallet)'), ('xysave', 'XySave (fallback Wallet)'), ('wallet', 'Wallet only')], default='auto', max_length=10),
        ),
    ]
