# Generated by Django 5.2.1 on 2025-08-12 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_charge_examplebankmodel_alter_bank_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsaving',
            name='account_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='Account Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetsaving',
            name='source',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('xysave', 'XySave Account'), ('both', 'Both (50/50)')], default='wallet', max_length=10, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='targetsaving',
            name='strict_mode',
            field=models.BooleanField(default=False, verbose_name='Strict Mode'),
        ),
        migrations.AddField(
            model_name='targetsavingdeposit',
            name='source',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('xysave', 'XySave Account'), ('both', 'Both (50/50)')], default='wallet', max_length=10, verbose_name='Source'),
        ),
        migrations.CreateModel(
            name='TargetSavingWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Withdrawal Amount')),
                ('destination', models.CharField(choices=[('wallet', 'Wallet'), ('xysave', 'XySave Account'), ('both', 'Both (50/50)')], default='wallet', max_length=10, verbose_name='Destination')),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('target_saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='bank.targetsaving')),
            ],
            options={
                'verbose_name': 'Target Saving Withdrawal',
                'verbose_name_plural': 'Target Saving Withdrawals',
                'ordering': ['-withdrawal_date'],
                'indexes': [models.Index(fields=['target_saving', 'withdrawal_date'], name='bank_target_target__18282f_idx')],
            },
        ),
    ]
