# Generated by Django 5.2.1 on 2025-08-13 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_targetsaving_account_number_targetsaving_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NightGuardSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('primary_method', models.CharField(default='face', max_length=20)),
                ('fallback_method', models.CharField(default='2fa', max_length=20)),
                ('applies_to', models.CharField(default='app_only', max_length=20)),
                ('face_template_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('face_template_alg', models.CharField(default='sha256', max_length=20)),
                ('face_registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='night_guard_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Night Guard Settings',
                'verbose_name_plural': 'Night Guard Settings',
                'db_table': 'bank_night_guard_settings',
            },
        ),
    ]
