# Generated by Django 5.2.1 on 2025-08-13 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_nightguardsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeTransactionShieldSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('per_transaction_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('face_template_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('face_template_alg', models.CharField(default='sha256', max_length=20)),
                ('face_registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='large_tx_shield_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Large Transaction Shield Settings',
                'verbose_name_plural': 'Large Transaction Shield Settings',
                'db_table': 'bank_large_tx_shield_settings',
            },
        ),
    ]
