# Generated by Django 5.2.1 on 2025-08-14 00:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_payoutrequest_paymentintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSettlementAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(max_length=128, unique=True)),
                ('bank_code', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, default='api', max_length=20)),
                ('preferred_schedule', models.CharField(blank=True, default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_merchant_settlement_account',
                'indexes': [models.Index(fields=['merchant_id'], name='bank_mercha_merchan_7f34c6_idx')],
            },
        ),
    ]
