# Generated by Django 5.2.1 on 2025-07-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_kycprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='FCM device token for push notifications', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Receive notifications via email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_in_app',
            field=models.BooleanField(default=True, help_text='Receive notifications in-app'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_push',
            field=models.BooleanField(default=False, help_text='Receive notifications via push'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_sms',
            field=models.BooleanField(default=False, help_text='Receive notifications via SMS'),
        ),
    ]
