# Generated by Django 5.2.1 on 2025-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_fcm_token_userprofile_notify_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Hashed transaction PIN', max_length=128, null=True),
        ),
    ]
