# Generated by Django 5.2.1 on 2025-06-26 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='Geographical latitude of the address', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Geographical longitude of the address', null=True, verbose_name='Longitude')),
                ('address', models.CharField(help_text='Full address including street, city, state, and postal code', max_length=255, verbose_name='Address')),
                ('city', models.CharField(help_text='City name', max_length=255, verbose_name='City')),
                ('state', models.CharField(help_text='State, province, or region', max_length=255, verbose_name='State')),
                ('country', models.CharField(help_text='Country', max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, help_text='Postal or ZIP code', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code', regex='^[A-Za-z0-9\\s\\-]+$')], verbose_name='Postal Code')),
                ('phone', models.CharField(help_text='Phone', max_length=100, verbose_name='Phone')),
                ('additional_phone', models.CharField(blank=True, help_text='Additional phone', max_length=100, null=True, verbose_name='Additional phone ')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default address", verbose_name='Default Address')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('school', 'School'), ('market', 'Market'), ('other', 'Other'), ('business', 'Business'), ('mailing', 'Mailing')], default='home', help_text='Type of address (home, office, etc.)', max_length=10, verbose_name='Address Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this address was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this address was last updated')),
                ('user', models.ForeignKey(help_text='The user this shipping address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='address_shi_user_id_7ad5bd_idx'), models.Index(fields=['user', 'created_at'], name='address_shi_user_id_159bc4_idx')],
            },
        ),
    ]
