# Generated by Django 5.2.1 on 2025-06-23 22:51

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Full address including street, city, state, and postal code', max_length=255, verbose_name='Address')),
                ('city', models.CharField(help_text='City name', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(default='12345', help_text='Postal or ZIP code', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code (e.g., 12345 or 12345-6789)', regex='^\\d{5}(-\\d{4})?$')], verbose_name='Postal Code')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None)),
                ('additional_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Additional contact phone number (optional)', max_length=128, null=True, region=None)),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default address", verbose_name='Default Address')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('school', 'School'), ('market', 'Market'), ('other', 'Other'), ('business', 'Business'), ('mailing', 'Mailing')], default='home', help_text='Type of address (home, office, etc.)', max_length=10, verbose_name='Address Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this address was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this address was last updated')),
                ('country', models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('state', models.ForeignKey(blank=True, help_text='State, province, or region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region')),
                ('user', models.ForeignKey(help_text='The user this shipping address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='address_shi_user_id_7ad5bd_idx'), models.Index(fields=['user', 'created_at'], name='address_shi_user_id_159bc4_idx')],
            },
        ),
    ]
