# Generated by Django 5.2.1 on 2025-06-23 23:58

import datetime
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default=datetime.datetime(2025, 6, 23, 23, 58, 9, 243580, tzinfo=datetime.timezone.utc), help_text='Country', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal or ZIP code', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code', regex='^[A-Za-z0-9\\s\\-]+$')], verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default=datetime.datetime(2025, 6, 23, 23, 58, 21, 636747, tzinfo=datetime.timezone.utc), help_text='State, province, or region', max_length=100, verbose_name='State'),
            preserve_default=False,
        ),
    ]
