# Generated by Django 5.2.1 on 2025-06-23 16:37

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='additional_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Additional contact phone number (optional)', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default=datetime.datetime(2025, 6, 23, 16, 37, 34, 927886, tzinfo=datetime.timezone.utc), help_text='Street address, P.O. box, company name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('school', 'School'), ('market', 'Market'), ('business', 'Business'), ('other', 'Other')], default='home', help_text='Type of address (Home, Work, Other)', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(help_text='City or town', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this address was created'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='full_name',
            field=models.CharField(help_text='Full name of the recipient', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default shipping address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(help_text='ZIP or postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.ForeignKey(blank=True, help_text='State, province, or region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this address was last updated'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(help_text='The user this shipping address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default'], name='address_shi_user_id_7ad5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'created_at'], name='address_shi_user_id_159bc4_idx'),
        ),
    ]
