# Generated by Django 5.2.1 on 2025-07-03 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shippingaddress',
            name='unique_default_address_per_user',
        ),
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='address_shi_user_id_e55fa0_idx',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='updated_by',
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
    ]
