# Generated by Django 5.2.1 on 2025-06-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='additional_phone',
            field=models.CharField(blank=True, help_text='Additional phone', max_length=100, null=True, verbose_name='Additional phone '),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone', max_length=100, null=True, verbose_name='Phone'),
        ),
    ]
