# Generated by Django 5.2.1 on 2025-06-23 17:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_shippingaddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(help_text='Full address including street, city, state, and postal code', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('school', 'School'), ('market', 'Market'), ('other', 'Other'), ('business', 'Business'), ('mailing', 'Mailing')], default='home', help_text='Type of address (home, office, etc.)', max_length=10, verbose_name='Address Type'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(help_text='City name', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Whether this is the user's default address", verbose_name='Default Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(default='12345', help_text='Postal or ZIP code', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code (e.g., 12345 or 12345-6789)', regex='^\\d{5}(-\\d{4})?$')], verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
