# Generated by Django 5.2.1 on 2025-06-24 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_shippingaddress_additional_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(help_text='City name', max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=datetime.datetime(2025, 6, 24, 0, 46, 10, 323255, tzinfo=datetime.timezone.utc), help_text='Phone', max_length=100, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(help_text='State, province, or region', max_length=255, verbose_name='State'),
        ),
    ]
