# Generated by Django 5.2.1 on 2025-06-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geographical latitude of the address', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geographical longitude of the address', null=True, verbose_name='Longitude'),
        ),
    ]
