# Generated by Django 5.2.1 on 2025-06-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='template_name',
        ),
    ]
