# Generated by Django 5.2.1 on 2025-07-04 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_cart_cart_cart_created_981ed1_idx'),
        ('product', '0001_initial'),
        ('store', '0006_remove_storestaff_store_store_role_59dbdf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_userId__7968f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_storeId_823d5a_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_by',
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_userId__e11d85_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['store'], name='cart_cart_storeId_0fb65a_idx'),
        ),
    ]
