# Generated by Django 5.2.1 on 2025-07-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_is_dele_1abc99_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
    ]
