# Generated by Django 5.2.1 on 2025-08-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('digital_wallet', 'Digital Wallet'), ('cryptocurrency', 'Cryptocurrency'), ('xysave', 'XySave Account'), ('wallet', 'Wallet')], help_text='Method used for payment', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('digital_wallet', 'Digital Wallet'), ('cryptocurrency', 'Cryptocurrency'), ('xysave', 'XySave Account'), ('wallet', 'Wallet')], help_text='Method used for payment', max_length=20, verbose_name='Payment Method'),
        ),
    ]
