# Generated by Django 5.2.1 on 2025-06-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
