# Generated by Django 5.2.1 on 2025-06-20 00:26

import uuid
from django.db import migrations, models


def generate_uuid(apps, schema_editor):
    """Generate UUIDs for existing records"""
    Order = apps.get_model('order', 'Order')
    Payment = apps.get_model('order', 'Payment')
    
    for order in Order.objects.all():
        order.new_id = uuid.uuid4()
        order.save(update_fields=['new_id'])
    
    for payment in Payment.objects.all():
        payment.new_id = uuid.uuid4()
        payment.save(update_fields=['new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_notes'),
    ]

    operations = [
        # Step 1: Add new UUID fields
        migrations.AddField(
            model_name='order',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Remove old primary key constraints
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        
        # Step 4: Rename new_id to id and make it primary key
        migrations.RenameField(
            model_name='order',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='new_id',
            new_name='id',
        ),
        
        # Step 5: Set as primary key
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ] 