# Generated by Django 5.2.1 on 2025-06-20 00:48

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_alter_address_postal_code'),
        ('order', '0004_alter_order_id_alter_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='extras.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(default=datetime.datetime(2025, 6, 20, 0, 48, 27, 320015, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(),
        ),
    ]
