# Generated by Django 5.2.1 on 2025-06-20 00:48

import uuid
from django.db import migrations, models


def generate_uuid(apps, schema_editor):
    """Generate UUIDs for existing OrderItem records"""
    OrderItem = apps.get_model('order', 'OrderItem')
    
    for order_item in OrderItem.objects.all():
        order_item.new_id = uuid.uuid4()
        order_item.save(update_fields=['new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_billing_address_and_more'),
    ]

    operations = [
        # Step 1: Add new UUID field
        migrations.AddField(
            model_name='orderitem',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        
        # Step 2: Generate UUIDs for existing records
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Remove old primary key
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        
        # Step 4: Rename new_id to id and make it primary key
        migrations.RenameField(
            model_name='orderitem',
            old_name='new_id',
            new_name='id',
        ),
        
        # Step 5: Set as primary key
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ] 